include:
- project: tq-em/common/ci
  file: apps.yml
  ref: v4.1.8_tc3.15.5

variables:
  GO111MODULE: "on"
  GOPRIVATE: "vgitlab01.tq-net.de"

Lint:
  extends: .go-lint

Code Generation:
  extends: .go-generate-code
