// Code generated by dbus-codegen-go. DO NOT EDIT.
//
// com.tq_group.tq_em.device_settings1.SerialControl
//   Methods
//     BindInterface
//     GetInterface
//     ListInterfaces
//     Reset
//     SetOperState
//     UnbindInterface
//
// org.freedesktop.DBus.Introspectable
//   Methods
//     Introspect
//
package device_settings

import (
	"log"

	"github.com/godbus/dbus"
)

const (
	methodPropertyGet = "org.freedesktop.DBus.Properties.Get"
	methodPropertySet = "org.freedesktop.DBus.Properties.Set"
)

// Avoid error caused by unused log import
var _ = log.Printf

// Interface is a DBus interface implementation.
type Interface interface {
	iface() string
}

// LookupInterface returns an interface for the named object.
func LookupInterface(object dbus.BusObject, iface string) Interface {
	switch iface {
	case InterfaceSerialControl:
		return NewSerialControl(object)
	case InterfaceOrg_Freedesktop_DBus_Introspectable:
		return NewOrg_Freedesktop_DBus_Introspectable(object)
	default:
		return nil
	}
}

// Signal is a common interface for all signals.
type Signal interface {
	Name() string
	Interface() string
	Sender() string
	Path() dbus.ObjectPath
}

// LookupSignal converts the given raw DBus signal into typed one or returns nil.
func LookupSignal(signal *dbus.Signal) Signal {
	switch signal.Name {
	default:
		return nil
	}
}

// AddMatchRule returns AddMatch rule for the given signal.
func AddMatchRule(sig Signal) string {
	return "type='signal',interface='" + sig.Interface() + "',member='" + sig.Name() + "'"
}

// Interface name constants.
const (
	InterfaceSerialControl                       = "com.tq_group.tq_em.device_settings1.SerialControl"
	InterfaceOrg_Freedesktop_DBus_Introspectable = "org.freedesktop.DBus.Introspectable"
)

// NewSerialControl creates and allocates com.tq_group.tq_em.device_settings1.SerialControl.
func NewSerialControl(object dbus.BusObject) *SerialControl {
	return &SerialControl{object}
}

// SerialControl implements com.tq_group.tq_em.device_settings1.SerialControl D-Bus interface.
type SerialControl struct {
	object dbus.BusObject
}

// iface implements the Interface interface.
func (o *SerialControl) iface() string {
	return InterfaceSerialControl
}

// BindInterface calls com.tq_group.tq_em.device_settings1.SerialControl.BindInterface method.
func (o *SerialControl) BindInterface(in0 string, in1 string, in2 string, in3 bool) (err error) {
	err = o.object.Call(InterfaceSerialControl+"."+"BindInterface", 0, in0, in1, in2, in3).Store()
	return
}

// GetInterface calls com.tq_group.tq_em.device_settings1.SerialControl.GetInterface method.
func (o *SerialControl) GetInterface(in0 string, in1 string) (out0 string, err error) {
	err = o.object.Call(InterfaceSerialControl+"."+"GetInterface", 0, in0, in1).Store(&out0)
	return
}

// ListInterfaces calls com.tq_group.tq_em.device_settings1.SerialControl.ListInterfaces method.
func (o *SerialControl) ListInterfaces(in0 string) (out0 map[string]byte, err error) {
	err = o.object.Call(InterfaceSerialControl+"."+"ListInterfaces", 0, in0).Store(&out0)
	return
}

// Reset calls com.tq_group.tq_em.device_settings1.SerialControl.Reset method.
func (o *SerialControl) Reset(in0 string, in1 string) (err error) {
	err = o.object.Call(InterfaceSerialControl+"."+"Reset", 0, in0, in1).Store()
	return
}

// SetOperState calls com.tq_group.tq_em.device_settings1.SerialControl.SetOperState method.
func (o *SerialControl) SetOperState(in0 string, in1 string, in2 byte) (err error) {
	err = o.object.Call(InterfaceSerialControl+"."+"SetOperState", 0, in0, in1, in2).Store()
	return
}

// UnbindInterface calls com.tq_group.tq_em.device_settings1.SerialControl.UnbindInterface method.
func (o *SerialControl) UnbindInterface(in0 string, in1 string) (err error) {
	err = o.object.Call(InterfaceSerialControl+"."+"UnbindInterface", 0, in0, in1).Store()
	return
}

// NewOrg_Freedesktop_DBus_Introspectable creates and allocates org.freedesktop.DBus.Introspectable.
func NewOrg_Freedesktop_DBus_Introspectable(object dbus.BusObject) *Org_Freedesktop_DBus_Introspectable {
	return &Org_Freedesktop_DBus_Introspectable{object}
}

// Org_Freedesktop_DBus_Introspectable implements org.freedesktop.DBus.Introspectable D-Bus interface.
type Org_Freedesktop_DBus_Introspectable struct {
	object dbus.BusObject
}

// iface implements the Interface interface.
func (o *Org_Freedesktop_DBus_Introspectable) iface() string {
	return InterfaceOrg_Freedesktop_DBus_Introspectable
}

// Introspect calls org.freedesktop.DBus.Introspectable.Introspect method.
func (o *Org_Freedesktop_DBus_Introspectable) Introspect() (out string, err error) {
	err = o.object.Call(InterfaceOrg_Freedesktop_DBus_Introspectable+"."+"Introspect", 0).Store(&out)
	return
}
